---
- hosts: all
  become: true
  become_user: root
  tasks:
   - name: Install multiple packages
     service:
      name: "{{ item }}"
      state: started
     
     ignore_errors: true
 
     with_items:
      - postfix
      - dovecot
      - httpd
      - samba
      - vsftpd
