---
- hosts: all
  become: true
  become_user: root
  tasks:
   
   - name: Install multiple packages
     yum:
      name: "{{ item }}"
      state: present
     ignore_errors: true    


     with_items:
      - httpd
      - vsftpd

   - name: Start Services
     service:
      name: "{{ item }}"
      state: running
      enabled: yes
     ignore_errors: true    
     
     with_items:
      - httpd
      - vsftpd
